# This workflow will build a Java project with Maven
name: Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  applications:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]

    runs-on: ${{ matrix.os }}

    env:
      JAVA_VERSION: ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Set JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: Generate Coverage Report
        run: cd prometheus-source-flink && mvn clean verify
      - name: Archive Jacoco reports
        uses: actions/upload-artifact@v2.2.4
        with:
          name: jacoco-reports
          path: test-coverage/target/site/jacoco-aggregate